# Generated by Django 4.1.4 on 2022-12-11 09:00

import accounts.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_attachments.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
		('auth', '0012_alter_user_first_name_max_length'),
		('django_attachments', '0003_attachment_options'),
	]

	operations = [
		migrations.CreateModel(
			name='User',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
				('password', models.CharField(max_length=128)),
				('last_login', models.DateTimeField(blank=True, null=True)),
				('is_superuser', models.BooleanField(default=False)),
				('username', models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
				('first_name', models.CharField(blank=True, max_length=150)),
				('last_name', models.CharField(blank=True, max_length=150)),
				('email', models.EmailField(blank=True, max_length=254)),
				('is_staff', models.BooleanField(default=False)),
				('is_active', models.BooleanField(default=True)),
				('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
				('links', models.TextField(blank=True)),
				('gallery', django_attachments.fields.GalleryField(on_delete=django.db.models.deletion.CASCADE, to='django_attachments.library')),
				('groups', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.group')),
				('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.permission')),
			],
			options={
				'abstract': False,
			},
			bases=(parler.models.TranslatableModelMixin, models.Model),
			managers=[
				('objects', accounts.models.UserManager()),
			],
		),
		migrations.CreateModel(
			name='UserTranslation',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
				('language_code', models.CharField(db_index=True, max_length=15)),
				('subtitle', models.CharField(max_length=100, blank=True)),
				('short_description', models.TextField(blank=True)),
				('description', models.TextField(blank=True)),
				('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL)),
			],
			options={
				'verbose_name': 'user Translation',
				'db_table': 'accounts_user_translation',
				'db_tablespace': '',
				'managed': True,
				'default_permissions': (),
				'unique_together': {('language_code', 'master')},
			},
			bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
		),
	]
