# Generated by Django 4.1.4 on 2022-12-11 09:00

import accounts.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_attachments.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
		('auth', '0012_alter_user_first_name_max_length'),
		('django_attachments', '0003_attachment_options'),
	]

	operations = [
		migrations.CreateModel(
			name='User',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('password', models.CharField(max_length=128, verbose_name='password')),
				('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
				('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
				('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
				('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
				('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
				('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
				('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
				('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
				('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
				('links', models.TextField(blank=True, help_text='Links to other sites e.g twitter: ...(newline)facebook: ...', verbose_name='Description')),
				('gallery', django_attachments.fields.GalleryField(on_delete=django.db.models.deletion.CASCADE, to='django_attachments.library')),
				('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
				('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
			],
			options={
				'abstract': False,
			},
			bases=(parler.models.TranslatableModelMixin, models.Model),
			managers=[
				('objects', accounts.models.UserManager()),
			],
		),
		migrations.CreateModel(
			name='UserTranslation',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
				('subtitle', models.CharField(max_length=100, verbose_name='Subtitle')),
				('short_description', models.TextField(verbose_name='Short description')),
				('description', models.TextField(blank=True, verbose_name='Description')),
				('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL)),
			],
			options={
				'verbose_name': 'user Translation',
				'db_table': 'accounts_user_translation',
				'db_tablespace': '',
				'managed': True,
				'default_permissions': (),
				'unique_together': {('language_code', 'master')},
			},
			bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
		),
	]
