# Generated by Django 4.1.4 on 2022-12-25 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_attachments.fields
import django_autoslugfield.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
		('django_attachments', '0003_attachment_options'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='BlogPost',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
				('date_created', models.DateTimeField(editable=False)),
				('date_updated', models.DateTimeField(editable=False)),
				('is_published', models.BooleanField(default=False)),
				('pub_time', models.DateTimeField(blank=True, db_index=True, null=True)),
				('attachments', django_attachments.fields.LibraryField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_attachments.library')),
				('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
				('gallery', django_attachments.fields.GalleryField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_attachments.library')),
			],
			options={
				'verbose_name': 'Blog post',
				'verbose_name_plural': 'Blog posts',
			},
			bases=(parler.models.TranslatableModelMixin, models.Model),
		),
		migrations.CreateModel(
			name='BlogPostTranslation',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
				('language_code', models.CharField(db_index=True, max_length=15)),
				('title', models.CharField(max_length=200)),
				('slug', django_autoslugfield.fields.AutoSlugField(in_respect_to=('language_code',), max_length=200, reserve_chars=0, title_field='title')),
				('summary', models.TextField(blank=True)),
				('perex', models.TextField(blank=True)),
				('content', models.TextField(blank=True)),
				('processed_content', models.TextField(blank=True, editable=False)),
				('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.blogpost')),
			],
			options={
				'verbose_name': 'Blog post Translation',
				'db_table': 'blog_blogpost_translation',
				'db_tablespace': '',
				'managed': True,
				'default_permissions': (),
				'unique_together': {('language_code', 'master')},
			},
			bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
		),
	]
