# Generated by Django 4.1.4 on 2022-12-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('blog', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='blogposttranslation',
			name='meta_description',
			field=models.TextField(blank=True),
		),
		migrations.AddField(
			model_name='blogposttranslation',
			name='page_title',
			field=models.CharField(blank=True, max_length=200),
		),
	]
