# Generated by Django 4.1.4 on 2022-12-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('blog', '0001_initial'),
	]

	operations = [
		migrations.AlterModelOptions(
			name='blogpost',
			options={'ordering': (models.OrderBy(models.F('pub_time'), descending=True, nulls_last=True), '-id'), 'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
		),
		migrations.AddField(
			model_name='blogposttranslation',
			name='meta_description',
			field=models.TextField(blank=True),
		),
		migrations.AddField(
			model_name='blogposttranslation',
			name='page_title',
			field=models.CharField(blank=True, max_length=200),
		),
		migrations.AlterIndexTogether(
			name='blogpost',
			index_together={('pub_time', 'id')},
		),
	]
